ignoreThrow: #don't throw bricks when right-clicking on these
    - 23 #dispenser
    - 54 #chest
    - 58 #crafting table
    - 61 #furnace
    - 62 #burning furnace
    - 69 #lever
    - 77 #stone button
    - 107 #fence gate
    - 117 #brewing stand
    - 143 #wooden button
    #- 145 #anvil
    #- 146 #trapped chest
    #- 149 #redstone comparator (inactive)
    #- 150 #redstone comparator (active)
    #- 154 #hopper
    #- 158 #dropper
    - 324 #wooden door
    - 328 #minecart
    - 342 #minecart with chest
    - 343 #minecart with furnace
    - 356 #repeater
    - 389 #item frame
    #- 407 #minecart with TNT
    #- 408 #minecart with hopper
brick:
    enabled: true
    velocity: 1.3
    damageDealt: 2
    armorDamage: 7
    destroyOnImpact: true
    breakMaterials: #materials the brick will break
        - 102 #thin glass
        - 20 #glass
molotov:
    enabled: true
    velocity: 1.1
    canBecomeFire: #materials that will be replaced with fire blocks
        - 0 #air
        - 31 #tall grass
        - 37 #dandelion
        - 38 #rose
        - 39 #brown mushroom
        - 40 #red mushroom
        - 50 #torch
        - 75 #redstone torch (inactive)
        - 76 #redstone torch (active)
        - 55 #redstone wire
grenade:
    enabled: true
    velocity: 0.9
    explosionStrength: 1.5